"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['../buildchimp.py']
DATA_FILES = []
OPTIONS = {'iconfile':'buildchimp.icns',
           'argv_emulation': True,
           'includes': ['PySide.QtCore', 'PySide.QtGui']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
